name: Push Content to Github Pages

on:
  push:
    branches:
      - main
      - dev
      - feature/*
  workflow_dispatch:
    inputs:
      dummy_input:
        required: false
        description: 'Dummy Input'
jobs:
  deploy_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com
          scope: '@team-obisidan'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run build
        run: |
          npm run build
      - name: Move to Github Pages
        run: |
          cd build
          find . -name '*.html' -exec cp --parents \{\} ../docs \;
          find . -name '*.css' -exec cp --parents \{\} ../docs \;
          find . -name '*.js' -exec cp --parents \{\} ../docs \;

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs
